spring.datasource.url=jdbc:postgresql://localhost:25432/gift
spring.datasource.username=gift
spring.datasource.password=gift
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=false
jwt.secret=a-string-secret-at-least-256-bits-long-for-test
cucumber.target.base-uri=http://localhost
cucumber.target.port=28080
