SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE orders RESTART IDENTITY;
TRUNCATE TABLE wish RESTART IDENTITY;
TRUNCATE TABLE options RESTART IDENTITY;
TRUNCATE TABLE product RESTART IDENTITY;
TRUNCATE TABLE member RESTART IDENTITY;
TRUNCATE TABLE category RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;
