SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE orders;
TRUNCATE TABLE wish;
TRUNCATE TABLE options;
TRUNCATE TABLE product;
TRUNCATE TABLE member;
TRUNCATE TABLE category;
SET REFERENTIAL_INTEGRITY TRUE;
