ALTER TABLE member ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE product ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE category ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE options ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
